AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  FileProcessorFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: java8
      Handler: com.verizon.vprice.serverless.FileProcessor::handleRequest
      Timeout: 60
      CodeUri: ./target/lambda.jar
